Add the function that keep current joint's value if it isn't set
rm-controls/rm_engineer pull request #13
Opened 2023-02-25 05:17 UTC by ljq-lv

为joints的设置添加了新的功能，当在steps中未设置某个位置的值的时候，程序默认为保持当前value位置，随之仅仅改变被修改的joints值，可用于操作手兑换时候调整直臂，或者其他灵活的变化使用

2023-02-25 12:14 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +          target_.push_back(motion["joints"][i]);
xmlrpc的数组似乎可以不同的数据类型混合。用999作为保持当前值的标记可能不直观且初看很困惑。不妨用`current_value`等之类的字符串来作为标记

2023-02-25 12:23 UTC, caijiefeng approved these changes

2023-02-25 14:37 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +
这样写target得是临时变量吧，你这每次执行都push_back一次，而且上面那个判断肯定一直return false

2023-02-26 14:07 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +          target_.push_back(KEEP);
检查是否为字符串且=="KEEP"？

2023-02-26 14:19 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +          target_.push_back(KEEP);
不好 这里就是不方便 字符串和double一起用 才用的宏定义KEEP 因为这里target是vector double

2023-02-26 14:21 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +          target_.push_back(KEEP);
> 

你else那里判断一下有什么难的，跟target是不是vector double 没有任何关系

2023-02-26 14:22 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +          target_.push_back(KEEP);
OO 你说加这个

2023-02-27 06:13 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +          target_.push_back(KEEP);
已改

2023-02-28 13:13 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +      }
最好有个断言，避免既不为数字，又不为字符串"KEEP"的情况出现

2023-02-28 13:28 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +      }
assert（motion["joints"][i] ！= “keep” || motion["joints"][i].getType() ！= XmlRpc::XmlRpcValue::TypeDouble ） 这样子写吗 没用过断言 然后放在第一个if前面  其实我之前 直接用else的话 就是在step里面需要保持的joints位置 写啥字符都可以表示保持当前位置 但就是在代码里面看不太出来

2023-02-28 13:46 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +      }
> assert（motion["joints"][i] ！= “keep” || motion["joints"][i].getType() ！= XmlRpc::XmlRpcValue::TypeDouble ） 这样子写吗 没用过断言 然后放在第一个if前面 其实我之前 直接用else的话 就是在step里面需要保持的joints位置 写啥字符都可以表示保持当前位置 但就是在代码里面看不太出来

第一行代码就是个断言啊和if一样的。主要就是防呆设计吧你永远不知道以后能因为参数搞出啥锅来

2023-03-01 04:52 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +      }
已加 且测试成功 有防呆功能

2023-03-01 05:28 UTC, ye-luo-xi-tui approved these changes

2023-03-02 14:01 UTC, qiayuanliao requested changes

2023-03-02 14:01 UTC, qiayuanliao commented on engineer_middleware/include/engineer_middleware/motion.h
> +#define KEEP 999
不要使用 宏，不要使用实际数字，可以用 NAN

2023-03-02 14:01 UTC, qiayuanliao commented on engineer_middleware/include/engineer_middleware/motion.h
> +#define KEEP 999
查阅 code style 可知道对于这种数据应该放在哪，应该叫什么，哪里大写不大写

2023-03-02 14:20 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +#define KEEP 999
收到

2023-03-04 01:29 UTC, ljq-lv commented
修改成NAN 并且成功了

2023-03-04 05:24 UTC, qiayuanliao approved these changes
OK，我还是第一次知道 std::isnormal 这个函数哈哈哈

2023-03-04 05:31 UTC, merged