Add stone_num, point_cloud, spaceEEMotion.
rm-controls/rm_engineer pull request #21
Opened 2023-05-17 09:23 UTC by L-SY

## 主要改动：

- 针对笛卡尔坐标系下的末端Motion解算概率较低的问题，增加了spaceEEMotion，通过增加Points类将发布的点改为球或者点，线，面，立方体。以此达到较高解算成功率的目的。

- ```
  void rectifyForRPY(double theta, double beta, double k_x, double k_theta, double k_beta)
  ```

​		其中这个函数是考虑到兑换框的姿态可能会导致规划的球体完全处于机械臂的可达空间外（比如说pitch仰角很大的时候，往后退0.5m那个点就会飞到天上，所以需要对应的给它一个往下的量）。配套参数文件如下：

```
  EXCHANGE_AUTO:
    - step: "auto exchange"
      arm:
        frame: exchanger
        xyz: [ -0.5, 0., 0. ]
        rpy: [ 0., -1.57, 0. ]
        rpy_rectify: [ 0.01,0.03,0.03 ]
        tolerance_position: 0.2
        tolerance_orientation: 0.2
        spacial_shape: SPHERE
        radius: 0.3
        point_resolution: 0.90
        max_planning_times: 100
        common:
          <<: *SLOWLY_LOW_TIMEOUT
```

#### 次要改动：

- 增加发布矿石数量
- 增加发布点云

2023-05-17 13:16 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/chassis_interface.h
> +    cmd_vel.linear.y = pid_y_.computeCommand(error.y, period) <= max_vel_ ? pid_y_.computeCommand(error.y, period) : 0;
为什么大于max_vel就直接设为0

2023-05-17 13:18 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/middleware.h
> +  geometry_msgs::TwistStamped test_;
这两个是啥玩意

2023-05-17 13:19 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/middleware.h
> +  tf::Transform transform;
发布什么的transform

2023-05-18 08:42 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/middleware.h
> +  geometry_msgs::TwistStamped test_;
没删干净

2023-05-18 08:43 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +  sensor_msgs::PointCloud2 getPointCloud2()
为什么有2

2023-05-18 08:44 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +      if (interface_.computeCartesianPath(waypoints, 0.01, 0.0, trajectory) < 99.9)
这里又变回去了？？

2023-05-18 14:34 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/chassis_interface.h
> +    cmd_vel.linear.y = pid_y_.computeCommand(error.y, period) <= max_vel_ ? pid_y_.computeCommand(error.y, period) : 0;
针对疯车问题，它可能突然会发一个很大的速度。

2023-05-18 14:35 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/chassis_interface.h
> +    cmd_vel.linear.y = pid_y_.computeCommand(error.y, period) <= max_vel_ ? pid_y_.computeCommand(error.y, period) : 0;
代码逻辑感觉都正确，目前不知道还有什么别的方法改这个问题。

2023-05-18 14:39 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/middleware.h
> +  tf::Transform transform;
没删干净，已删除。

2023-05-18 14:40 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/middleware.h
> +  geometry_msgs::TwistStamped test_;
ok已删除。

2023-05-18 14:40 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/middleware.h
> +  geometry_msgs::TwistStamped test_;
之前测试使用的，已删除。

2023-05-18 14:59 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/planning_scene.h
> -      std::cout << planning_scene_interface_.getAttachedObjects().size() << std::endl;
这个删了 有可能会 碰撞箱无法直接生成 被链接的物体喔

2023-05-18 15:01 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +    if (motion.hasMember("frame"))
这里的初始化不需要给个默认值吗 如果没填写的话 不就不正确了 要不就直接报错缺少 要不就有个默认值

2023-05-18 15:03 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +    }
这里的motion的命名要不要再详细一点 position和xyz 初看分不清二者差异 而且为什么xyz又不同判断type了

2023-05-18 15:09 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/step_queue.h
> +      queue_.emplace_back(steps[i], scenes, tf, arm_group, chassis_interface, hand_pub, join7_pub, stone_num_pub,
不要叫joint7 pub 而且还拼错了 把joint7这些都换个具体意义的名称

2023-05-18 15:14 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
> +    ROS_ASSERT(motion.hasMember("frame"));
这部分的初始化都是

2023-05-18 16:02 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/step_queue.h
> +      queue_.emplace_back(steps[i], scenes, tf, arm_group, chassis_interface, hand_pub, end_effector_pub, stone_num_pub,
1

2023-05-18 18:27 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +  std_msgs::Int32 judgePlanningResult()
又经典回退版本？

2023-05-18 18:30 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +    if (!target_.header.frame_id.empty())
为什么删掉，有无影响 @ljq-lv

2023-05-18 18:32 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +        else
干嘛删掉

2023-05-18 18:37 UTC, ye-luo-xi-tui commented on engineer_middleware/src/middleware.cpp
> +  , end_effector_pub_(nh.advertise<std_msgs::Float64>("/controllers/joint7_controller/command", 10))
joint7_controller也改一下？

2023-05-18 19:26 UTC, L-SY reviewed
1

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +      if (interface_.computeCartesianPath(waypoints, 0.01, 0.0, trajectory) < 99.9)
已调整。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/planning_scene.h
> -      std::cout << planning_scene_interface_.getAttachedObjects().size() << std::endl;
OK已经加回去了。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/planning_scene.h
> -      std::cout << planning_scene_interface_.getAttachedObjects().size() << std::endl;
OK已经加回去咯。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/step_queue.h
> +      queue_.emplace_back(steps[i], scenes, tf, arm_group, chassis_interface, hand_pub, join7_pub, stone_num_pub,
已修改，名字那个似乎没有更适合的名字了。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +    if (motion.hasMember("frame"))
已经改成没有报错了，给默认值似乎不好给。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +    }
改了下，将position换成xyz，xyz换成basics_length,因为它对应类型为BASICS，即空间中的基础类型，点线面体。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/step_queue.h
> +      queue_.emplace_back(steps[i], scenes, tf, arm_group, chassis_interface, hand_pub, join7_pub, stone_num_pub,
改成joint7_position_pub感觉好点。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/step_queue.h
> +      queue_.emplace_back(steps[i], scenes, tf, arm_group, chassis_interface, hand_pub, join7_pub, stone_num_pub,
> 不要叫joint7 pub 而且还拼错了 把joint7这些都换个具体意义的名称

已改为end_effector_pub

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/planning_scene.h
> -      std::cout << planning_scene_interface_.getAttachedObjects().size() << std::endl;
已修改。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/planning_scene.h
> -      std::cout << planning_scene_interface_.getAttachedObjects().size() << std::endl;
已修改

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +    ROS_ASSERT(motion.hasMember("frame"));
确实，已经删除重复部分。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/step_queue.h
> +      queue_.emplace_back(steps[i], scenes, tf, arm_group, chassis_interface, hand_pub, end_effector_pub, stone_num_pub,
1

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/src/middleware.cpp
> +  , end_effector_pub_(nh.advertise<std_msgs::Float64>("/controllers/joint7_controller/command", 10))
这对应改到controller config里去了，joint7放到那个里面感觉比较合适，因为前面有joint1，joint2那些。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +  std_msgs::Int32 judgePlanningResult()
ok已修改

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +    if (!target_.header.frame_id.empty())
删了为了可以对link6进行规划，jq哥修改的。

2023-05-18 19:26 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +        else
确实没必要

2023-05-18 19:28 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +        else
确实没必要删除，已经加回去了

2023-05-19 18:36 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
> +  ros::Duration t = ros::Duration(0.2);
不应该作为成员变量，用到它的地方搞个局部变量就可以了

2023-05-19 18:37 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/points.h
> +      // cloud.channels[0].values[i] = i;
不要有注释

2023-05-20 06:15 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +  ros::Duration t = ros::Duration(0.2);
确实，已修改。

2023-05-20 06:15 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/points.h
> +      // cloud.channels[0].values[i] = i;
已删除。

2023-05-20 10:19 UTC, qiayuanliao commented
spaceEeMotion 而非 spaceEEMotion，下头！

2023-05-20 14:31 UTC, qiayuanliao requested changes

2023-05-20 14:31 UTC, qiayuanl commented on engineer_middleware/include/engineer_middleware/chassis_interface.h
> +    cmd_vel.linear.y = pid_y_.computeCommand(error.y, period) <= max_vel_ ? pid_y_.computeCommand(error.y, period) : 0;
> 针对疯车问题，它可能突然会发一个很大的速度。

谁突然发一个很大的速度？
你是在说pid突然算出来一个很大的速度吧？

这个问题不可能解决不了！！！

2023-05-20 14:31 UTC, qiayuanliao commented on engineer_middleware/include/engineer_middleware/motion.h
> +      z_length_ = xmlRpcGetDouble(motion["basics_length"], 2);
这是啥意思

2023-05-21 04:51 UTC, L-SY commented
> spaceEeMotion 而非 spaceEEMotion，下头！

已改为SpaceEeMotion。

2023-05-21 04:52 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +      z_length_ = xmlRpcGetDouble(motion["basics_length"], 2);
三个方向上的长度。

2023-05-21 04:53 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +      z_length_ = xmlRpcGetDouble(motion["basics_length"], 2);
![Uploading Screenshot from 2023-05-16 21-04-11.png…]()
![Screenshot from 2023-05-16 21-04-56](https://github.com/rm-controls/rm_engineer/assets/54620791/5701a055-90ee-43a5-a610-6da8935f863b)
![Uploading Screenshot from 2023-05-16 21-05-52.png…]()

2023-05-21 04:54 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +      z_length_ = xmlRpcGetDouble(motion["basics_length"], 2);
用来实现从规划点到空间中的线面体。

2023-05-21 04:55 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/motion.h
> +  sensor_msgs::PointCloud2 getPointCloud2()
因为它是CloudPoint2，和点云1区分一下。

2023-05-21 04:57 UTC, L-SY commented on engineer_middleware/include/engineer_middleware/chassis_interface.h
> +    cmd_vel.linear.y = pid_y_.computeCommand(error.y, period) <= max_vel_ ? pid_y_.computeCommand(error.y, period) : 0;
准备分区赛后验证是map坐标系突然飞了海斯period有问题

2023-05-21 15:57 UTC, ye-luo-xi-tui commented
@qiayuanliao

2023-05-23 13:53 UTC, ye-luo-xi-tui commented
@qiayuanliao

2023-05-25 16:17 UTC, qiayuanliao commented
> > spaceEeMotion 而非 spaceEEMotion，下头！
> 
> 已改为SpaceEeMotion。

pr 标题没改，下头！

我明天看所有pr。

2023-05-25 16:17 UTC, qiayuanliao commented on engineer_middleware/include/engineer_middleware/motion.h
> +      z_length_ = xmlRpcGetDouble(motion["basics_length"], 2);
明白了，看起来不错！

2023-05-26 04:13 UTC, ye-luo-xi-tui commented
pr ddl: 2023.5.26

2023-05-26 17:39 UTC, qiayuanliao approved these changes
不错，想出“尝试求解兑换姿态附近的一大堆点”确实是个好方法。
希望分区赛之后好好改进。

2023-05-26 18:15 UTC, merged