Add planning_scece on engineer's control
rm-controls/rm_engineer pull request #4
Opened 2022-05-29 15:34 UTC by ljq-lv

2022-05-29 15:35 UTC, ljq-lv commented
ci format好像是 我写的之外的代码 报的错

2022-05-31 03:21 UTC, qiayuanliao commented
> ci format好像是 我写的之外的代码 报的错

你看清楚好吧...

2022-05-31 10:09 UTC, YuuinIH commented
CI的问题已经修好了。

2022-06-06 15:07 UTC, qiayuanliao requested changes

2022-06-06 15:07 UTC, qiayuanl commented on engineer_middleware/include/engineer_middleware/step_queue.h
> +            const XmlRpc::XmlRpcValue& scene)
为什么不把  `const XmlRpc::XmlRpcValue& scene` 放在 `const XmlRpc::XmlRpcValue& steps` 后面？

2022-06-06 15:07 UTC, qiayuanl commented on engineer_middleware/src/middleware.cpp
> +    XmlRpc::XmlRpcValue xml_value1;
找屌？？

2022-06-06 15:07 UTC, qiayuanl commented on engineer_middleware/include/engineer_middleware/step.h
> +       ros::Publisher& gimbal_pub, const XmlRpc::XmlRpcValue& scenes)
为什么不把  `const XmlRpc::XmlRpcValue& scene` 放在 `const XmlRpc::XmlRpcValue& steps` 后面？

2022-06-06 15:07 UTC, qiayuanliao commented on engineer_middleware/config/steps_list.yaml
> +        name: "TEST_BOX"
你这再套一层的意义是什么？为什么不叫：

`scene: "TEST_BOX"` 或者 `scene_name: "TEST_BOX"`，

2022-06-06 15:07 UTC, qiayuanliao commented on engineer_middleware/config/scenes_list.yaml
> +    - id: "big"
我不太理解为什么要引入 `object_ids` 的机制

每一个 step 应该对应到一个 'scence' 场景，然后每个场景里面都有好几个 object，这些object 同时添加或同时删除，为什么需要给每个 object id？

2022-06-06 15:11 UTC, ljq-lv commented on engineer_middleware/config/scenes_list.yaml
> +    - id: "big"
因为删除的方式是匹配object id的方法去删除某个object，而不是删除同一个场景里的所有objects。

2022-06-06 15:14 UTC, qiayuanliao commented on engineer_middleware/config/scenes_list.yaml
> +    - id: "big"
你自己在程序里面生成并记录某一个场景里面的所有 object id 分别是什么呀，不需要用户在配置文件里面写吧？

2022-06-06 15:22 UTC, qiayuanl commented on engineer_middleware/config/scenes_list.yaml
> +    - id: "big"
可以先别改 我觉得你没时间了

2022-06-06 16:11 UTC, qiayuanliao approved these changes

2022-06-06 16:11 UTC, merged