Update 22 season engineer's code
rm-controls/rm_engineer pull request #5
Opened 2022-07-09 14:02 UTC by ljq-lv

2022-07-09 14:03 UTC, ljq-lv commented
step list 里面的东西还要调整下 现在因为tolerance没设置好的原因 大多数动作做不出来

2022-07-15 10:23 UTC, qiayuanl commented
CI 没过

2022-07-25 13:47 UTC, ljq-lv commented
fomat的错是因为 yaml文件里面不允许用两个keymap；然后ci的错误是moveit那边的构建有问题

2022-07-26 16:03 UTC, qiayuanliao commented
@ye-luo-xi-tui 有点蛋疼，太多了，你先看一下

2022-07-26 16:04 UTC, qiayuanliao commented
@ljq-lv 把commit合并一下吧

2022-07-27 07:53 UTC, ye-luo-xi-tui commented
先把commit合并一下吧

2022-07-27 07:56 UTC, ljq-lv commented
已经合并了  976d62c 是合并后的了

2022-07-27 07:58 UTC, ye-luo-xi-tui commented
> 已经合并了 [976d62c](https://github.com/rm-controls/rm_engineer/commit/976d62c713c4f740bbb12435948b5ea19c416c14) 是合并后的了

没有啊

2022-07-27 08:00 UTC, ljq-lv commented
![Screenshot from 2022-07-27 15-59-43](https://user-images.githubusercontent.com/47436322/181194198-4cbadd75-00d7-4894-a90d-9fd71bd426e2.png)

2022-07-27 08:04 UTC, ye-luo-xi-tui commented
> ![Screenshot from 2022-07-27 15-59-43](https://user-images.githubusercontent.com/47436322/181194198-4cbadd75-00d7-4894-a90d-9fd71bd426e2.png)

合并完还有132个属实离谱，format没过哦。

2022-07-27 08:06 UTC, ljq-lv commented
> 

那是因为他还是算的上面所有的132 commit  format 没过还是那个keymap的原因  要想过的话就只能把step list 里面 用两个keymap的地方 删掉一处用的了 但是就显得非常复杂了

2022-07-28 07:46 UTC, qiayuanliao requested changes
为什么要有 engineer.urdf ???!!! 这不是你生成ikfast而用的临时文件吗？  第一眼就发现一个大错，你commit之前都不看我看什么？？

2022-10-14 15:35 UTC, ye-luo-xi-tui commented on engineer_middleware/config/steps_list.yaml
> +        <<: *BIGGER_TOLERANCE
为什么是重复的

2022-10-14 15:42 UTC, ye-luo-xi-tui commented on engineer_middleware/config/steps_list.yaml
> +        <<: *BIGGER_TOLERANCE
> 为什么是重复的

没事了

2022-10-14 15:44 UTC, ye-luo-xi-tui commented on engineer_middleware/config/steps_list.yaml
> +    - step: "add scene of sky island"
能解释一下sky island是啥玩意吗，还有LF之类的实在百思不得其解

2022-10-14 15:53 UTC, ye-luo-xi-tui commented on engineer_middleware/config/steps_list.yaml
> +  gripper:
为什么是夹爪？不是吸盘吗？

2022-10-15 02:48 UTC, ljq-lv commented on engineer_middleware/config/steps_list.yaml
> +    - step: "add scene of sky island"
在资源岛 空接 LF RT这些代表是对应位置 左中右

2022-10-15 02:50 UTC, ljq-lv commented on engineer_middleware/config/steps_list.yaml
> +  gripper:
我理解成末端负责搞物体的装置就统一都用gripper了

2022-10-15 02:50 UTC, ljq-lv commented
后面我把fomat的问题解决一下先

2022-10-15 04:32 UTC, ye-luo-xi-tui commented on engineer_middleware/config/steps_list.yaml
> +    - step: "add scene of sky island"
认真按照英文语法写吧，麻了

2022-10-15 04:32 UTC, ye-luo-xi-tui commented on engineer_middleware/config/steps_list.yaml
> +    - step: "add scene of sky island"
> 

什么吕式英语

2022-10-15 04:39 UTC, ljq-lv commented on engineer_middleware/config/steps_list.yaml
> +    - step: "add scene of sky island"
又不是按英语语法写的，这样名名字是为了按键逻辑好处理

2022-10-15 04:42 UTC, ye-luo-xi-tui commented on engineer_middleware/config/steps_list.yaml
> +    - step: "add scene of sky island"
> 又不是按英语语法写的，这样名名字是为了按键逻辑好处理

LF_BIG_ISLAND0我就不管你了，我说的是“add scene of sky island”

2022-10-22 11:55 UTC, Aung-xiao approved these changes

2022-10-22 13:16 UTC, caijiefeng approved these changes

2022-10-27 02:34 UTC, ljq-lv commented
@ye-luo-xi-tui @1moule @chenhuiYu00 @NaHCO3bc @L-SY @Edwinlinks

2022-10-28 02:23 UTC, ljq-lv commented
@ye-luo-xi-tui @1moule @chenhuiYu00 @NaHCO3bc @L-SY @Edwinlinks

2022-10-28 13:03 UTC, ljq-lv commented
@ye-luo-xi-tui @1moule @chenhuiYu00 @NaHCO3bc @L-SY @Edwinlinks qy哥催我勒

2022-10-28 17:40 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
>  #include <engineer_middleware/chassis_interface.h>
没找到这个头文件

2022-10-28 17:47 UTC, ljq-lv commented on engineer_middleware/include/engineer_middleware/motion.h
>  #include <engineer_middleware/chassis_interface.h>
你说的哪个嘞，moveit那个吗

2022-10-28 17:48 UTC, ye-luo-xi-tui commented on engineer_middleware/include/engineer_middleware/motion.h
>  #include <engineer_middleware/chassis_interface.h>
> 你说的哪个嘞，moveit那个吗

engineer_middleware/chassis_interface.h

2022-10-28 18:19 UTC, ye-luo-xi-tui reviewed
看着没啥问题，解答一下我提出的问题吧

2022-10-29 01:26 UTC, ljq-lv commented
> 看着没啥问题，解答一下我提出的问题吧

a那个文件没有被修改过 所有file change看不到

2022-10-29 02:51 UTC, ye-luo-xi-tui commented
> > 看着没啥问题，解答一下我提出的问题吧
> 
> a那个文件没有被修改过 所有file change看不到

那没事了

2022-10-29 02:52 UTC, ye-luo-xi-tui approved these changes

2022-10-29 11:50 UTC, NaHCO3bc approved these changes

2022-10-29 11:52 UTC, 1moule approved these changes

2022-10-29 12:02 UTC, L-SY approved these changes

2022-10-29 14:33 UTC, ye-luo-xi-tui commented
@chenhuiYu00 @Edwinlinks

2022-10-30 04:01 UTC, ljq-lv commented
@chenhuiYu00 @Edwinlinks

2022-10-31 05:54 UTC, ljq-lv commented
@chenhuiYu00 @Edwinlinks

2022-10-31 06:46 UTC, caijiefeng approved these changes

2022-10-31 12:09 UTC, ye-luo-xi-tui commented
@chenhuiYu00 @Edwinlinks

2022-11-02 16:32 UTC, chenhuiYu00 approved these changes

2022-11-03 02:50 UTC, qiayuanliao approved these changes

2022-11-03 02:50 UTC, qiayuanliao commented on engineer_arm_config/config/ur_simulated_config.yaml
>  ###############################################
文件名？

2022-11-03 03:03 UTC, qiayuanliao requested changes
engineer_arm_config/config/ur_simulated_config.yaml

2022-11-03 03:03 UTC, qiayuanliao requested changes
engineer_arm_config/config/ur_simulated_config.yaml

2022-11-03 05:19 UTC, qiayuanliao approved these changes

2022-11-03 09:25 UTC, merged